import { createFileRoute, isRedirect, redirect } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { Check, KeyRound, Link2, Mail, ShieldCheck, UserRound } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { ErrorState, LoadingState, PageTitle } from "@/components/page-kit";
import { getAuthMethods, getSession } from "@/lib/api.functions";

export const Route = createFileRoute("/account")({ beforeLoad: async () => { try { if (!(await getSession())) throw redirect({ to: "/" }); } catch (error) { if (isRedirect(error)) throw error; throw redirect({ to: "/" }); } }, head: () => ({ meta: [{ title: "Account — Roommate Roulette" }, { name: "description", content: "Review your Roommate Roulette identity and sign-in methods." }, { property: "og:title", content: "Account — Roommate Roulette" }, { property: "og:description", content: "Review your Roommate Roulette identity and sign-in methods." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: AccountPage });

function AccountPage(){const fetchMethods=useServerFn(getAuthMethods);const query=useQuery({queryKey:["auth-methods"],queryFn:()=>fetchMethods()});if(query.isLoading)return <AppShell><LoadingState/></AppShell>;if(query.error)return <AppShell><ErrorState message={query.error.message}/></AppShell>;const user=query.data;if(!user)return null;const methods=[{label:"Password",enabled:user.has_password,icon:KeyRound},{label:"Google",enabled:user.has_google_auth,icon:Link2},{label:"Ed25519 key",enabled:user.has_ed25519,icon:ShieldCheck}];return <AppShell><PageTitle index="03" title="Account" description="Identity record and connected authentication methods."/><div className="grid gap-8 lg:grid-cols-[1fr_1fr]"><section className="border border-border bg-surface p-6 shadow-brutal-purple md:p-8"><div className="mb-7 grid size-16 place-items-center border border-primary bg-primary font-grotesk text-2xl font-bold uppercase text-primary-foreground">{user.full_name.slice(0,2)}</div><p className="font-mono text-[10px] uppercase text-muted-foreground">Profile record</p><h2 className="mt-2 font-grotesk text-3xl font-bold uppercase">{user.full_name}</h2><div className="mt-7 divide-y divide-border border-y border-border"><div className="flex items-center gap-3 py-4"><Mail className="size-4 text-secondary"/><span className="font-mono text-sm">{user.email}</span></div><div className="flex items-center gap-3 py-4"><UserRound className="size-4 text-secondary"/><span className="font-mono text-xs text-muted-foreground">{user.user_id}</span></div></div><p className="mt-5 font-mono text-[10px] uppercase text-muted-foreground">Profile editing is not provided by the current API.</p></section><section className="border border-border bg-surface-dark"><div className="border-b border-border p-6"><p className="font-mono text-[10px] uppercase text-accent">Security matrix</p><h2 className="mt-2 font-grotesk text-2xl font-bold uppercase">Login methods</h2></div>{methods.map(({label,enabled,icon:Icon})=><div key={label} className="flex items-center gap-4 border-b border-border p-5 last:border-b-0"><Icon className="size-5 text-secondary"/><span className="font-medium">{label}</span><span className={`ml-auto flex items-center gap-2 font-mono text-[10px] uppercase ${enabled?"text-accent":"text-muted-foreground"}`}>{enabled&&<Check className="size-3"/>}{enabled?"Connected":"Not connected"}</span></div>)}</section></div></AppShell>}